apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-deployment
  labels:
    app: oms-app
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oms-app
  template:
    metadata:
      labels:
        app: oms-app
    spec:
      containers:
        - name: tomcat-deploy
          image: chocoman55/tomcat_oms:latest 
          ports:
            - containerPort: 8080